name: filmo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  get_it: ^7.2.0 # dependencia de get_it
  url_launcher: ^6.3.1
  url_launcher_web: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/imagenes/ #acceso às imagens
